#!/bin/sh
# SAMPLE APPLICATION
# FLOPPINUX EDITION SCRIPT
#

# COVER
cat /app/cover
read -p "_______PRESS_ENTER" input

while true; do
clear
cat /app/toc
read -p "_______CHOOSE:" doit
clear

case $doit in
  0) exit ;;
  c) cat /home/cover ;;
  1) cat /home/txt/intro.txt | less ;;
  2) cat /home/txt/why-pi.txt | less ;;
  3) cat /home/txt/perfect-editor.txt | less ;;
  4) cat /home/txt/floppinux.txt | less ;;
  *) clear ;;esac
done
